### ISSUE TITLE
General tips regarding cleaner code

### ISSUE THREAD

**Issue by Bios-Marcel** [dakyskye/GitHub-Trayer#1]
It's very uncommon to have a constructor modify static state. This will never allow you to have multiple instances of a class that work independently from each other. While not causing an issue, it's considered an anti pattern. Either change everything to be static or making everything instance fields.

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L17

This method should be inlined, as it's only called once and isn't very long. Also I'd move the content to the end of the constructor.

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L34

This code is duplicated, consider making a method:

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L41

Sometimes you use the `final` keyword and sometimes you don't. I recommend consistently using it, as it avoids accidentally overwriting variables. Every decision to overwrite will be on purpose this way, as you'll have to manually remove the final again.

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L55

Consider joining variable declaration and initialization. Reduces clutter imho and makes clear in which scope a variable is used.
Try to always keep the scope as big as necessary and as small as possible.

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L59

You are on a background thread here, accessing the Swing thread (AWTEventQueue), potentially causing issues. Consider adding `SwingUtilities#invokeLater`. If your timer was to run more often and in parallel, you'd get race conditions due to the fact you are increasing a static variable.

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L69

Same story regarding use of static here:

https://github.com/dakyskye/GitHub-Trayer/blob/2c1f67ea463397b6fd40e62aa8a900e2ee2b2f00/src/main/java/com/github/dakyskye/github_trayer/App.java#L74

**Comment by dakyskye** [comment]
Thanks a lot for all these suggestions! I'll bear that in mind and fix my code bit later 👍
